### ISSUE TITLE
Latest commit (7aa5789ab87c3f816829ab0ad4ffe6899484fdb4) has broken blob_test.go

### ISSUE THREAD

**Issue by jf** [MSOpenTech/azure-sdk-for-go#10]
https://github.com/MSOpenTech/azure-sdk-for-go/blob/master/clients/storage/blob_test.go#L637 should now be
```if expected := base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%011d", 0))); thatBlock.Name != expected {```

Commit in question: 7aa5789ab87c3f816829ab0ad4ffe6899484fdb4

**Comment by hopetobelievein** [comment]
@ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
ah forgot to update the tests. my bad. @jf wanna submit a pr or want me to do it. fix looks lgtm.

**Comment by jf** [comment]
Thanks for asking, @ahmetalpbalkan. I'll do a PR shortly. I may end up following development somewhat closely, so it's just as well.

**Comment by ahmetalpbalkan** [comment]
@jf ok feel free to submit a PR. @hopetobelievein can help merging.

**Comment by hopetobelievein** [comment]
Fixed by https://github.com/MSOpenTech/azure-sdk-for-go/pull/11
