### ISSUE TITLE
Consider having a stateful client object

### ISSUE THREAD

**Issue by jen20** [MSOpenTech/azure-sdk-for-go#27]
I know the current design is similar in design to the node CLI tools, but I'd like to open up a discussion about moving to having a stateful client object which represents the subscription currently being worked on and has methods for the various operations.

This would greatly assist automation which affects multiple subscriptions simultaneously (which at the moment would need to be in separate processes). It's a fairly significant refactoring, I can dedicate some time to looking at it if the consensus is that it's desirable however.

**Comment by ahmetalpbalkan** [comment]
cc: @paulmey
we were thinking of the same, storage client is currently stateful and does not contain any globals. however other parts usually work with globals, which prevents working with multiple subscriptions in the same process.

**Comment by paulmey** [comment]
Yes, this has been a silent wish of mine too. I agree it's probably a big refactor and most probably breaks current consumers, so we'll probably have to start versioning the codebase. We could keep both models side-by-side for a while to help consumers transition.

**Comment by jen20** [comment]
Closed by #41.
