### ISSUE TITLE
Proposal: rename 'azure' directory to 'clients'

### ISSUE THREAD

**Issue by ahmetalpbalkan** [MSOpenTech/azure-sdk-for-go#45]
Current status results in a weird import path like:

    go get github.com/MSOpenTech/azure-sdk-for-go/azure/storage

that's better off  as `/clients/` as it used to be like in v1.x

**Comment by ahmetalpbalkan** [comment]
Better idea:

```
└── core/
└──  management/
    ├──hostedservice/
    ├──storageservice/
    ├──...
    ├──virtualmachine/
    └──virtualnetwork/
└──storage/
    ├──blob/
    ├──table/      (not yet implemented)
    └──queue/      (not yet implemented)
```

how's that sound? cc: @jeffmendoza @hopetobelievein @brendandixon

**Comment by jen20** [comment]
That looks better to me, certainly.

**Comment by hopetobelievein** [comment]
Yeah, that makes much more sense.
And we should probably update readme, it still uses 'azure' directory.
