### ISSUE TITLE
management.NewClientFromPublishSettings is undefined

### ISSUE THREAD

**Issue by waitingkuo** [MSOpenTech/azure-sdk-for-go#58]
According to README.md
We can use 

    client, err := management.NewClientFromPublishSettings(SUBSCRIPTION_ID, SUBSCRIPTION_CERTIFICATE)
        if err != nil {
            fmt.Println(err)
            os.Exit(1)
        }

to create a client.

But NewClientFromPublishSettings is undefined.

**Comment by hopetobelievein** [comment]
Updated readme.
Now we can use:
<code>subscriptionCert, err := ioutil.ReadFile(SUBSCRIPTION_CERTIFICATE_PATH)
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }

    client, err := management.NewClient(SUBSCRIPTION_ID, subscriptionCert)
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
</code>

**Comment by waitingkuo** [comment]
Thanks, it works!
Is it possible to use the publishsettings file to create the client?
#57

**Comment by anweiss** [comment]
@ahmetalpbalkan Since we made cert handling the responsibility to the caller, how do we want to provide for .publishsettings handling?

**Comment by jen20** [comment]
@anweiss In my opinion this library should handle the `.publishsettings` files as it's Azure specific.

**Comment by ahmetalpbalkan** [comment]
@jen20 +1. We need the wa

**Comment by waitingkuo** [comment]
According to the current architecture, i've made a patch
3c9cf2fecccf6bbbedbc117ac48c12f381536e02

**Comment by ahmetalpbalkan** [comment]
@waitingkuo can you please send a pull request? We should probably add another constructor that takes Config as well and one should call another (just like what we have today)

**Comment by paulmey** [comment]
fixed in #65 /  ea0d561
