### ISSUE TITLE
rename AddAzureLinuxProvisioningConfig

### ISSUE THREAD

**Issue by ahmetalpbalkan** [MSOpenTech/azure-sdk-for-go#60]
this should be NewAzureLinuxProvisioningConfig. anyone?

**Comment by hopetobelievein** [comment]
Well it takes VM configuration and adds Linux provisioning config to it. Result is updated VM config, not Linux provisioning config. 
I named it identically to Add-AzureProvisioningConfig cmdlet from Azure powershell.

**Comment by ahmetalpbalkan** [comment]
Sounds fair except we should eventually remove such client side logic eventually.
